### PR TITLE
Vignettes

### PR DESCRIPTION
**Pull request by friendly**
Add my new vignettes branch for work on, well, vignettes.

### CODE REVIEW

**Comment by djmurphy420** [comment]
Hi Michael:
Why didn't I think of that? Brilliant idea - I'm in!
Dennis 

    On Tuesday, October 3, 2017 9:29 AM, Michael Friendly <notifications@github.com> wrote:
 

 Add my new vignettes branch for work on, well, vignettes.
You can view, comment on, or merge this pull request online at:
  https://github.com/cdalzell/Lahman/pull/33
Commit Summary
   
   - create vignettes branch, initialize use_vignette("dummy")
   - initialize vignettes with dummy.Rmd

File Changes
   
   -  M .gitignore (2) 
   -  M DESCRIPTION (6) 
   -  A vignettes/dummy.Rmd (58) 

Patch Links:
   
   - https://github.com/cdalzell/Lahman/pull/33.patch
   - https://github.com/cdalzell/Lahman/pull/33.diff

**Comment by friendly** [comment]
Uh oo...  This is telling me that I merged `vignettes` into `master`, which wasn't what I had intended.

**Comment by cdalzell** [comment]
Yeah, noticed that yesterday. I'd prefer to keep master what's available on CRAN, but we can work around that. No worries.

**Comment by friendly** [comment]
We are back on track.  See #34 for the workflow going forward.

**Pull request merged**
